### ISSUE TITLE
Adding a GE12730 Fan Control as a Switch or a Leviton R04-DZR15-1RZ Outlet crashes Homebridge 

### ISSUE THREAD

**Issue by PrestonEJ** [mike182uk/homebridge-zwave#22]
Stack trace from the logs - appears to be the same for either device.

[11/9/2019, 9:06:09 PM] [ZWavePlatform] Master Bedroom Fan "On" characteristic value requested
[11/9/2019, 9:06:09 PM] TypeError: Cannot destructure property `value` of 'undefined' or 'null'.
    at /usr/lib/node_modules/homebridge-zwave/lib/AccessoryManager.js:556:13
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge-zwave/lib/AccessoryManager.js:540:21)
    at Characteristic.emit (events.js:210:5)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:210:5)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)

[11/9/2019, 8:26:30 PM] [ZWavePlatform] Master Bedroom Outlet "Outlet In Use" characteristic value requested
[11/9/2019, 8:26:30 PM] TypeError: Cannot destructure property `value` of 'undefined' or 'null'.
    at /usr/lib/node_modules/homebridge-zwave/lib/AccessoryManager.js:556:13
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge-zwave/lib/AccessoryManager.js:540:21)
    at Characteristic.emit (events.js:210:5)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:210:5)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)

Happy to troubleshoot or provide any additional info I can - I'm way out of my depth trying to dig into this on my end, unfortunately.

**Comment by mike182uk** [comment]
Hmm, it's most likely not compatible as just a switch.

Do you have a link to the exact accessory so I could dig a little deeper?

**Comment by PrestonEJ** [comment]
https://byjasco.com/products/ge-z-wave-plus-wall-smart-fan-control

https://www.leviton.com/en/products/dzr15-1rz
