### ISSUE TITLE
TypeError during findNodeValue (related to node-openzwave-shared version?)

### ISSUE THREAD

**Issue by alexford** [mike182uk/homebridge-zwave#41]
Hello! Thank you for writing and maintaining this plugin. I'm hoping someone out there can help identify what I'm doing wrong here, or perhaps there's a bug.  I'm having trouble getting this plugin to pick up my only Z-Wave device.

I'm new to Z-Wave, and pretty familiar with Homebridge and Node/JS. I'm using Homebridge 1.1.1.

Using `node-openzwave-shared` on its own, in a REPL, I added this device as node 4 and I can toggle it on and off normally.

However, when I add it to Homebridge using this plugin (see config below), a TypeError is thrown and Homebridge crashes/restarts in a loop. The zwave devicePath is set correctly (same as I'm using in the Node REPL), and I double checked that Node 4 is what works there, too.

_I'm wondering if perhaps something changed in the more recent releases of `node-openzwave-shared`? Just a hunch as the error seems like something I'd expect if APIs mismatched. Semantically there shouldn't be breaking changes in 1.7.x but stranger things have happened?_

_Or, is Homebridge 1.x.x not supported yet?_

---

Homebridge platform config:

```json
{
            "platform": "ZWavePlatform",
            "name": "ZWavePlatform",
            "zwave": {
                "devicePath": "/dev/cu.usbmodem411"
            },
            "accessories": [
                {
                    "zwaveNodeId": 4,
                    "displayName": "Can Lights",
                    "homekitCategory": "Switch",
                    "homekitServices": [
                        "Switch"
                    ]
                }
            ],
            "noCache": false
        },
```

---

Homebridge output:

```
[7/14/2020, 7:46:51 AM] [ZWavePlatform] Initializing new accessories...
[7/14/2020, 7:46:51 AM] [ZWavePlatform] Can Lights initialized!
Initialising OpenZWave 1.6.1207 binary addon for Node.JS.
	OpenZWave Security API is ENABLED
	ZWave device db    : /usr/local/etc/openzwave
	User settings path : /Users/aford/.nvm/versions/node/v12.18.2/lib/node_modules/homebridge-zwave/node_modules/openzwave-shared/build/Release/../../
	Option Overrides : --Logging false --SaveConfiguration false
[7/14/2020, 7:46:53 AM] TypeError: Cannot destructure property 'value' of 'this._zwave.findNodeValue(...)' as it is undefined.
    at /Users/aford/.nvm/versions/node/v12.18.2/lib/node_modules/homebridge-zwave/lib/AccessoryManager.js:102:22
    at EventEmitter.<anonymous> (/Users/aford/.nvm/versions/node/v12.18.2/lib/node_modules/homebridge-zwave/lib/ZWave.js:76:9)
    at EventEmitter.emit (events.js:315:20)
    at ZWave._ozwNodeReady (/Users/aford/.nvm/versions/node/v12.18.2/lib/node_modules/homebridge-zwave/lib/ZWave.js:193:24)
    at OZW.emit (events.js:315:20)
```

**Comment by mike182uk** [comment]
Hey @alexford 

So it look like its failing to retrieve the serial number from the device:

https://github.com/mike182uk/homebridge-zwave/blob/8c3ef40f0e51bba49bd19d1909b6a537026b7337/lib/AccessoryManager.js#L102-L105

Are you able to confirm if the device actually exposes a serial number via the REPL?

What version of `open-zwave` do you have installed? (this plugin has only been tested with `1.6`).

I've not tested this on `Homebridge 1.x.x` but thats not likely to be the culprit here

**Comment by alexford** [comment]
Thanks for the quick reply. It's`open-zwave` 1.6.1207

I don't see a serial number listed, but I'm not sure I know exactly where to expect it. Here is the output I see about the node in the REPL.

First, while querying:

```
2020-07-14 07:24:01.481 Detail, Node004, Notification: NodeQueriesComplete
2020-07-14 07:24:01.481 Detail, contrlr, Notification: AllNodesQueried
node4: GE (Jasco Products), 14292 In-Wall Smart Toggle Switch
node4: name="", type="On/Off Power Switch", location=""
node4: class 37
node4:   Switch=true
node4: class 39
node4:   Switch All=On and Off Enabled
node4: class 43
node4:   Scene=0
node4:   Duration=0
node4: class 94
node4:   ZWave+ Version=1
node4:   InstallerIcon=1792
node4:   UserIcon=1792
node4: class 112
node4:   Invert Switch=No
node4: class 114
node4:   Loaded Config Revision=4
node4:   Config File Revision=4
node4:   Latest Available Config File Revision=4
node4: class 115
node4:   Powerlevel=Normal
node4:   Timeout=0
node4:   Set Powerlevel=undefined
node4:   Test Node=0
node4:   Test Powerlevel=Normal
node4:   Frame Count=0
node4:   Test=undefined
node4:   Report=undefined
node4:   Test Status=Failed
node4:   Acked Frames=0
node4: class 134
node4:   Library Version=3
node4:   Protocol Version=4.54
node4:   Application Version=5.21
====> scan complete
```


Then, as `nodes[4]`:

```js
{
    manufacturer: 'GE (Jasco Products)',
    manufacturerid: '0x0063',
    product: '14292 In-Wall Smart Toggle Switch',
    producttype: '0x4952',
    productid: '0x3037',
    type: 'On/Off Power Switch',
    name: '',
    loc: '',
    classes: {
      '37': [Object],
      '39': [Object],
      '43': [Object],
      '94': [Object],
      '112': [Object],
      '114': [Object],
      '115': [Object],
      '134': [Object]
    },
    ready: true
  }
```

**Comment by mike182uk** [comment]
Hm, yeah i would of expected serial number to show up under `class 114`. I've possibly incorrectly assumed that all devices would expose a serial number. Are you able to modify the source code for the plugin? If so, modifying:

https://github.com/mike182uk/homebridge-zwave/blob/8c3ef40f0e51bba49bd19d1909b6a537026b7337/lib/AccessoryManager.js#L96-L112

so that the serial number retrieval does not fail:

```js
// Update the accessory information service with the latest ZWave node information 
const zwaveNodeId = accessoryConfig.zwaveNodeId 
 
this._zwave.onNodeReady(zwaveNodeId, zwaveNode => { 
  this._accessoryReadyState = READY_STATE_READY 
 
  this._configureAccessoryInformationService( 
    zwaveNode.manufacturer, 
    zwaveNode.product
  ) 
}) 
```

should hopefully get you up and running 🤞 

I'll have to dig a little deeper to see if the serial number is something we can assume is always present or not in order to get a proper fix for this.

**Comment by alexford** [comment]
That did work thank you! Is the serial number used for anything inside the plugin once set?

**Comment by mike182uk** [comment]
Great stuff 👍 

It is only used for displaying the device serial number in the device settings screen in HomeKit. The serial number for the device will just be set to `Unknown` in this case. It shouldn't affect any functionality or anything.
